const colors = {
  light: {
    text: '#0A0A0A',
    tint: '#22C55E',
    background: '#FAFAFA',
    foreground: '#0A0A0A',
    card: '#FFFFFF',
    cardForeground: '#0A0A0A',
    primary: '#22C55E',
    primaryForeground: '#FFFFFF',
    secondary: '#F3F3F3',
    secondaryForeground: '#0A0A0A',
    muted: '#F3F3F3',
    mutedForeground: '#8A8A8A',
    accent: '#F0FBF4',
    accentForeground: '#166534',
    destructive: '#EF4444',
    destructiveForeground: '#FFFFFF',
    border: '#EBEBEB',
    input: '#F3F3F3',
  },
  dark: {
    text: '#F5F5F5',
    tint: '#22C55E',
    background: '#0A0A0A',
    foreground: '#F5F5F5',
    card: '#141414',
    cardForeground: '#F5F5F5',
    primary: '#22C55E',
    primaryForeground: '#FFFFFF',
    secondary: '#1A1A1A',
    secondaryForeground: '#F5F5F5',
    muted: '#1A1A1A',
    mutedForeground: '#686868',
    accent: '#0F2B1A',
    accentForeground: '#86EFAC',
    destructive: '#EF4444',
    destructiveForeground: '#FFFFFF',
    border: '#1F1F1F',
    input: '#1A1A1A',
  },
  radius: 14,
};

export default colors;
